---
- name: "Deploy Redis"
  hosts: "{{ tower_env | default([]) }}"
  gather_facts: true
  become: true
  become_method: sudo
  become_user: root

  tasks:
    
    - name: "Install Redis"
      when: inv_install_redis | default(false)
      block:
        - name: "Include labocbz.prepare_host"
          tags:
            - "labocbz.prepare_host"
          vars:
            prepare_host_system_users: "{{ inv_prepare_host_redis_system_users }}"
          ansible.builtin.include_role:
            name: "labocbz.prepare_host"

        - name: "Include labocbz.add_certificates"
          tags:
            - "labocbz.add_certificates"
          loop: "{{ inv_install_redis_cert_bundles }}"
          loop_control:
            loop_var: bundle
          when: inv_install_redis_cert_bundles is defined
          vars:
            add_certificates_bundle_name: "{{ bundle.name }}"
            add_certificates_bundle_type: "{{ bundle.type }}"
            add_certificates_bundle_src: "{{ bundle.src }}"
            add_certificates_bundle_dest: "{{ bundle.dest }}"
            add_certificates_bundle_src_user: "{{ bundle.src_user }}"
            add_certificates_bundle_src_password: "{{ bundle.src_password }}"
            add_certificates_bundle_dest_user: "{{ bundle.dest_user }}"
            add_certificates_bundle_dest_group: "{{ bundle.dest_group }}"
            add_certificates_bundle_dest_mode: "{{ bundle.dest_mode }}"
          ansible.builtin.include_role:
            name: "labocbz.add_certificates"

        - name: "Include labocbz.install_redis"
          tags:
            - "labocbz.install_redis"
          loop: "{{ inv_install_redis_ports }}"
          loop_control:
            loop_var: port
          vars:
            install_redis_bind: "{{ inv_install_redis_bind }}"
            install_redis_port: "{{ port }}"
            install_redis_proteced_mode: "{{ inv_install_redis_proteced_mode }}"
            install_redis_loglevel: "{{ inv_install_redis_loglevel }}"
            install_redis_requirepass: "{{ inv_install_redis_requirepass }}"
            install_redis_cluster: "{{ inv_install_redis_cluster }}"
            install_redis_path: "{{ inv_install_redis_path }}"
            install_redis_conf: "{{ inv_install_redis_conf }}"
            install_redis_ssl: "{{ inv_install_redis_ssl }}"
            install_redis_ssl_domain: "{{ inv_install_redis_ssl_domain }}"
            install_redis_ssl_path: "{{ inv_install_redis_ssl_path }}"
            install_redis_ssl_key: "{{ inv_install_redis_ssl_key }}"
            install_redis_ssl_cert: "{{ inv_install_redis_ssl_cert }}"
            install_redis_ssl_ca: "{{ inv_install_redis_ssl_ca }}"
            install_redis_ssl_auth_client: "{{ inv_install_redis_ssl_auth_client }}"
          ansible.builtin.include_role:
            name: "labocbz.install_redis"

        - name: "Include labocbz.add_logrotate_confs"
          tags:
            - "labocbz.add_logrotate_confs"
          vars:
            logrotate_configurations: "{{ inv_logrotate_redis_configurations }}"
          ansible.builtin.include_role:
            name: "labocbz.add_logrotate_confs"
