---
- name: "Deploy Redis"
  hosts: "{{ tower_env | default([]) }}"
  gather_facts: true
  become: true
  become_method: sudo
  become_user: root

  tasks:
    
    - name: "Install Redis"
      when: inv_install_redis | default(false)
      block:
        - name: "Include labocbz.prepare_host"
          tags:
            - "labocbz.prepare_host"
          vars:
            prepare_host__system_users: "{{ inv_prepare_host__redis_system_users }}"
          ansible.builtin.include_role:
            name: "labocbz.prepare_host"

        - name: "Include labocbz.add_certificates"
          tags:
            - "labocbz.add_certificates"
          loop: "{{ inv_install_redis__cert_bundles }}"
          loop_control:
            loop_var: bundle
          when: inv_install_redis__cert_bundles is defined
          vars:
            add_certificates__bundle_name: "{{ bundle.name }}"
            add_certificates__bundle_type: "{{ bundle.type }}"
            add_certificates__bundle_src: "{{ bundle.src }}"
            add_certificates__bundle_dest: "{{ bundle.dest }}"
            add_certificates__bundle_src_user: "{{ bundle.src_user }}"
            add_certificates__bundle_src_password: "{{ bundle.src_password }}"
            add_certificates__bundle_dest_user: "{{ bundle.dest_user }}"
            add_certificates__bundle_dest_group: "{{ bundle.dest_group }}"
            add_certificates__bundle_dest_mode: "{{ bundle.dest_mode }}"
          ansible.builtin.include_role:
            name: "labocbz.add_certificates"

        - name: "Include labocbz.install_redis"
          tags:
            - "labocbz.install_redis"
          vars:
            install_redis__user: "{{ inv_install_redis__user }}"
            install_redis__group: "{{ inv_install_redis__group }}"
            install_redis__bind: "{{ inv_install_redis__bind }}"
            install_redis__port: "{{ inv_install_redis__port }}"
            install_redis__proteced_mode: "{{ inv_install_redis__proteced_mode }}"
            install_redis__loglevel: "{{ inv_install_redis__loglevel }}"
            install_redis__requirepass: "{{ inv_install_redis__requirepass }}"
            install_redis__cluster: "{{ inv_install_redis__cluster }}"
            install_redis__cluster_port: "{{ inv_install_redis__cluster_port }}"
            install_redis__initial_master: "{{ inv_install_redis__initial_master }}"
            install_redis__initial_mastername: "{{ inv_install_redis__initial_mastername }}"
            install_redis__sentinel_port: "{{ inv_install_redis__sentinel_port }}"
            install_redis__log_path: "{{ inv_install_redis__log_path }}"
            install_redis__logfile: "{{ inv_install_redis__logfile }}"
            install_redis__ssl: "{{ inv_install_redis__ssl }}"
            install_redis__ssl_domain: "{{ inv_install_redis__ssl_domain }}"
            install_redis__ssl_path: "{{ inv_install_redis__ssl_path }}"
            install_redis__ssl_key: "{{ inv_install_redis__ssl_key }}"
            install_redis__ssl_cert: "{{ inv_install_redis__ssl_cert }}"
            install_redis__ssl_client_auth: "{{ inv_install_redis__ssl_client_auth }}"
            install_redis__ssl_ca: "{{ inv_install_redis__ssl_ca }}"
          ansible.builtin.include_role:
            name: "labocbz.install_redis"

        - name: "Include labocbz.add_logrotate_confs"
          tags:
            - "labocbz.add_logrotate_confs"
          vars:
            add_logrotate_confs__files: "{{ inv_add_logrotate_confs__redis_configurations }}"
          ansible.builtin.include_role:
            name: "labocbz.add_logrotate_confs"
